### ISSUE TITLE
image scoller toont niet alle afbeeldingen

### ISSUE THREAD

**Issue by samalloing** [libis/cag_tools#106]
In object_id (29659) wordt niet alle afbeeldingen getoond in de image scroller. Misschien is het beter om de aanpassingen van de digitoolurl hier ook door te voeren (https://github.com/libis/ca_cag/issues/1)

cc @roxannewyns

**Comment by aruijmen** [comment]
De digitool implementatie werd ondertussen ook hier aangepast.
Voor wat betreft de niet getoonde afbeeldingen verwijs ik naar issue libis/ca_crkc#43
Oorzaak blijkt (cfr Sam) locale_id is NULL ipv locale_id = 1 voor het digitoolUrl element.
Heb dit rechtstreeks aangepast in de databank.
Heb in de interface de optie 'gebruik de taalinstelling niet' uitgevinkt voor het metadata-element digitoolUrl.
