### ISSUE TITLE
importeren access database 'veldwerk' in ca_cag 

### ISSUE THREAD

**Issue by roxannewyns** [libis/cag_tools#108]
assigned @aruijmen 

De access database 'veldwerk.mdb' moet geimporteerd worden in ca_cag in collectie 'traject landbouw).
- Access database 'veldwerk.mdb' op L schijf Heron > CAG > updateDatamodel
- MappingAdlibDC_veldwerk_v2.xlsx (werkblad 'Landbouw') op L schijf Heron > CAG

**Comment by aruijmen** [comment]
De gegevens van veldwerk werden geïmporteerd in cag.
Als bijlage een tekstbestand met de opgetreden error's.

1. veroorzaakt door foutieve schrijfwijzes, niet voorziene schrijfwijzes of onlogische combinaties die niet voorzien waren.

Oorzaak van 2, 3 en 4:
door '-' teken in zoekterm van collectie wordt deze door de REST-api niet gevonden (- wordt vervangen door [blank] 
maak ik kan dit nog oplossen, want de collectie is wel degelijk aangemaakt.  Je zegt het maar .....

Anita
