### ISSUE TITLE
type id doesn't get cleared in advanced search

### ISSUE THREAD

**Issue by samalloing** [libis/cag_tools#95]
In the advanced search it is difficult to clear the type_id with the preferences set to "Clear previous search terms when performing a new search or browse". Strange enough if you set your preferences to "Retain previous search terms and results when performing a search or browse", it is cleared :-)
cc @roxannewyns

**Comment by roxannewyns** [comment]
When searching on "algemene info", the simple search takes the right type
![capture](https://cloud.githubusercontent.com/assets/3798589/10015337/dc649c56-611f-11e5-9630-368b676698cf.JPG)
When clicking on advanced search the setting of the type should be 'algemene info', yet it takes type 'object' instead. Resetting doesn't help.
![capture](https://cloud.githubusercontent.com/assets/3798589/10015393/2619cd58-6120-11e5-9d27-e876e90d4577.JPG)

**Comment by aruijmen** [comment]
Dit werd veroorzaakt door het niet meenemen van het type_id als parameter.
Een aanpassing in de conf file: navigation.conf was hiervoor voldoende.
In de parameters sectie van de navigatie diende overal
parameter:type_id= ,
toegevoegd te worden, opdat men binnen hetzelfde subtype bleef bij switchen tussen basic/advanced search.
Ook hiervoor zal nog een pullrequest gemaakt worden naar CA toe.
De wijzigingen (inclusief deze voor RESET-button werden doorgevoerd op de poduktie.
